---

- name: linux package management
  hosts: "{{ nodes }}"

  tasks:

    - name: "set {{ package_list }} to {{ package_state }}"
      ansible.builtin.package:
        name: "{{ package_list }}"
        state: "{{ package_state }}"

...
