---

- name: configure windows optional features
  hosts: "{{ nodes }}"

  tasks:

    - name: "manage windows optional features"
      ansible.windows.win_optional_feature:
        name: "{{ optional_feature }}"
        state: present

# here's a sample of configuring more than 1 feature at a time
#      - name: "Enable Telnet Client and .Net 3.5"
#        win_optional_feature:
#          name:
#            - TelnetClient
#            - NetFx3
#          state: present

...
