---

- name: update windows servers
  hosts: "{{ nodes }}"

  tasks:

#    - name: Download and Install Windows Updates
#      win_updates:
#        category_names:
#          - Application
#          - Connectors
#          - Critical Updates
#          - Definition Updates
#          - Developer Kits
#          - Feature Packs
#          - Guidance
#          - Security Updates
#          - Service Packs
#          - Tools
#          - Update Rollups
#          - Updates
#          - Upgrades
#        whitelist:
#          - KB4093120
#        reboot: no
#        reboot_timeout: 600

    - name: process windows updates
      ansible.windows.win_updates:
        category_names: "{{ update_category }}"
        reboot: "{{ reboot_system | default(true) }}"
        reboot_timeout: "{{ reboot_timeout | default('3600') }}"
      when: not check_only

    - name: search windows updates
      ansible.windows.win_updates:
        category_names: "{{ update_category }}"
        state: searched
        log_path: C:\windows_updates.txt
      when: check_only

...
