---

- name: configure windows optional features
  hosts: "{{ nodes }}"

  vars:
    feature_optional: "{{ feature_optional | default(false) }}"
    include_management_tools: "{{ include_management_tools | default(true) }}"
    include_sub_features: "{{ include_sub_features | default(true) }}"
    reboot_system: "{{ reboot_system | default(true) }}"

  tasks:

    - name: manage windows optional feature
      ansible.windows.win_optional_feature:
        name: "{{ windows_feature }}"
        state: "{{ feature_state }}"
      when: feature_optional

# here's a sample of configuring more than 1 feature at a time
#      - name: "Enable Telnet Client and .Net 3.5"
#        win_optional_feature:
#          name:
#            - TelnetClient
#            - NetFx3
#          state: present

    - name: manage windows feature
      ansbile.windows.win_feature:
        name: "{{ windows_feature }}"
        state: "{{ feature_state }}"
        restart: "{{ reboot_system }}"
        include_sub_features: "{{ include_sub_features }}"
        include_management_tools: "{{ include_management_tools }}"
      when: not feature_optional

...
